# Generated by Django 3.2.5 on 2021-07-23 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interval', models.IntegerField(default=5)),
                ('last_run_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('should_run', models.BooleanField(default=True)),
            ],
        ),
    ]
