# Generated by Django 3.2.6 on 2021-08-26 21:33

import core.enums.run_status
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interval', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('last_run_datetime', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('should_run', models.BooleanField(default=True)),
                ('plugin_dest', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('VIRTUALENV', 'Creating virtual environment'), ('DEPENDECIES', 'Installing dependencies'), ('SUCCESS', 'Success'), ('Failed', 'Failed')], max_length=11, null=True)),
                ('stdout', models.TextField(null=True)),
                ('stderr', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PluginSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_dest', models.CharField(max_length=1000)),
                ('source_hash', models.CharField(max_length=512)),
                ('upload_time', models.DateTimeField()),
                ('upload_user', models.CharField(max_length=200)),
                ('source_file_hash', jsonfield.fields.JSONField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PluginRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdout', models.TextField(null=True)),
                ('stderr', models.TextField(null=True)),
                ('execute_start_time', models.DateTimeField()),
                ('execute_duration', models.DurationField(null=True)),
                ('run_status', models.CharField(choices=[('FAILED', 'Failed'), ('HASH_FAILED', 'Hash Failed'), ('SUCCESS', 'Success'), ('TIMED_OUT', 'Timed Out')], default=core.enums.run_status.RunStatus['SUCCESS'], max_length=11)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.plugin')),
            ],
        ),
        migrations.AddField(
            model_name='plugin',
            name='plugin_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pluginsource'),
        ),
    ]
