# Generated by Django 3.2.6 on 2021-08-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginsource',
            old_name='source_hash_timestamp',
            new_name='source_hash',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pluginsource'),
        ),
    ]
