# Generated by Django 3.2.6 on 2021-08-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='plugin_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pluginsource'),
        ),
    ]
