# Generated by Django 3.2.6 on 2021-08-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210826_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginrun',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='plugin_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pluginsource'),
        ),
        migrations.AlterField(
            model_name='pluginrun',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plugin'),
        ),
    ]
