# Generated by Django 3.2.6 on 2021-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210807_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='hash_name',
            field=models.CharField(default='undefined', max_length=512),
        ),
        migrations.AddField(
            model_name='plugin',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
