# Generated by Django 3.2.6 on 2021-09-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210827_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='name',
            new_name='plugin_name',
        ),
        migrations.AlterField(
            model_name='pluginsource',
            name='upload_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
