# Generated by Django 3.2.6 on 2021-08-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plugin_plugin_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginrun',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.plugin'),
        ),
    ]
