# Generated by Django 3.2.6 on 2021-08-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plugin_python_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='python_path',
            new_name='venv_dest',
        ),
    ]
