# Generated by Django 3.2.6 on 2021-08-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pluginrun_plugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='plugin_source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.pluginsource'),
        ),
        migrations.AlterField(
            model_name='pluginrun',
            name='execute_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='pluginrun',
            name='stderr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pluginrun',
            name='stdout',
            field=models.TextField(null=True),
        ),
    ]
