# Generated by Django 3.2.6 on 2021-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_python_path_plugin_venv_dest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plugin',
            old_name='venv_dest',
            new_name='plugin_dest',
        ),
    ]
